export const GET_PODCASTS_BY_PODCASTER = 'GET_PODCASTS_BY_PODCASTER';
export const SET_PAGE = 'SET_PAGE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_PODCAST_STATUS = 'SET_PODCAST_STATUS';
export const GET_PODCASTS_FILTER = 'GET_PODCASTS_FILTER';
export const SET_PODCASTS_FILTER = 'SET_PODCASTS_FILTER';
export const RESET_PODCASTS_FILTER = 'RESET_PODCASTS_FILTER';
export const RESET_PAGE = 'RESET_PAGE';
