export const SET_AUDIO_PLAYER = 'SET_AUDIO_PLAYER';
export const CLOSE_AUDIO_PLAYER = 'CLOSE_AUDIO_PLAYER';
export const NEXT_AUDIO = 'NEXT_AUDIO';
export const PREVIOUS_AUDIO = 'PREVIOUS_AUDIO';
export const PLAY_AUDIO_TRACK = 'PLAY_AUDIO_TRACK';
export const PAUSE_AUDIO_TRACK = 'PAUSE_AUDIO_TRACK';
