export const PODCASTER_LOGIN = 'PODCASTER_LOGIN';
export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL';
export const LISTENER_LOGIN = 'LISTENER_LOGIN';
export const ADVERTISER_LOGIN = 'ADVERTISER_LOGIN';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_AUDIO_EDITOR_EPISODES_COUNT = 'SET_AUDIO_EDITOR_EPISODES_COUNT';
