export const GET_SEARCH_PODCASTS = 'GET_SEARCH_PODCASTS';
export const SET_PAGE = 'SET_PAGE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SIZE = 'SET_SIZE';
export const FETCH_HOME_PAGE_DATA_START = 'FETCH_HOME_PAGE_DATA_START';
export const FETCH_HOME_PAGE_DATA_SUCCESS = 'FETCH_HOME_PAGE_DATA_SUCCESS';
export const FETCH_HOME_PAGE_DATA_ERROR = 'FETCH_HOME_PAGE_DATA_ERROR';
